# Generated by Django 4.0 on 2022-01-09 19:09

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_address_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(blank=True, max_length=6, validators=[users.models.validate_zip_code]),
        ),
    ]
